# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-09 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='index/')),
                ('image_name', models.CharField(default='', max_length=20)),
                ('image_caption', models.TextField(max_length=150)),
                ('likes', models.IntegerField(default=0, null=True)),
                ('comments', models.CharField(max_length=200)),
            ],
        ),
    ]
