# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-10 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='share',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
