# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-11 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_auto_20190311_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_image',
            field=models.ImageField(blank=True, upload_to='comment/'),
        ),
    ]
