# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-11 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0006_comment_comment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
