# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-11 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0007_comment_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileRecipients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=tinymce.models.HTMLField(),
        ),
    ]
